**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [3]:
marks = [9, 12, 4, 7, 9, 3, 12, 11, 4, 1, 5];

np_marks = np.array(marks);
print(np_marks)

[ 9 12  4  7  9  3 12 11  4  1  5]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [4]:
price = [[15, 3, 56, 78],
         [16, 2, 45, 100],
         [14, 4, 33, 94],
         [15, 6, 67, 240]
]

price_mas = np.array(price)
print(price_mas)

[[ 15   3  56  78]
 [ 16   2  45 100]
 [ 14   4  33  94]
 [ 15   6  67 240]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print("Data type of first array: ", np_marks.dtype.name)
print("Data type of second array: ", price_mas.dtype.name)

Data type of first array:  int64
Data type of second array:  int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:
print("Shape of first array: ", np_marks.shape)
print("Shape of second array: ", price_mas.shape)

Shape of first array:  (11,)
Shape of second array:  (4, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [7]:
week_money_earning = np.linspace(0, 1000.50, 7)
print("Money income during week: ", week_money_earning)

Money income during week:  [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [8]:
firsMas = np.array([10, 3, 1])
secondMas = np.array([2, 5, 8])

vertical = np.vstack((firsMas, secondMas))
horizontal = np.hstack((firsMas, secondMas))
print("Vertical combination:", vertical)
print("Horizontal combination:", horizontal)

Vertical combination: [[10  3  1]
 [ 2  5  8]]
Horizontal combination: [10  3  1  2  5  8]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [9]:
def transponMas(mas):
  """
    Functoin for transposing an masive
  """
  return mas.reshape(mas.shape[::-1]);

array = np.array([[2, 4, 6], [5, 3, 1]])
transponMas = transponMas(array)
print(f"Transposed array from: \n {array}, \n to: \n {transponMas}")

Transposed array from: 
 [[2 4 6]
 [5 3 1]], 
 to: 
 [[2 4]
 [6 5]
 [3 1]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [10]:
adding = firsMas + secondMas;
subtracting = firsMas - secondMas;
multiplicating = firsMas * 10;
elementwise_multiplicating = firsMas * secondMas;
matrix_multiplicating = firsMas.T @ secondMas;

print("The element-by-element addition operation: ", adding);
print("The element-by-element subtracting operation: ", subtracting);
print("Multiplicating operation: ", multiplicating);
print("Elementwise multiplicating operation: ", elementwise_multiplicating);
print("Matrix multiplicating operation: ", matrix_multiplicating);

The element-by-element addition operation:  [12  8  9]
The element-by-element subtracting operation:  [ 8 -2 -7]
Multiplicating operation:  [100  30  10]
Elementwise multiplicating operation:  [20 15  8]
Matrix multiplicating operation:  43


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [11]:
matrix = [[15, 3, 56, 78],
         [16, 2, 45, 100],
         [14, 4, 33, 94],
         [15, 6, 67, 240]
];

matrix_np = np.array(matrix);
min_number = matrix_np.min();
max_number = matrix_np.max();
min_of_each_row = matrix_np.min(axis=1);
max_of_each_row = matrix_np.max(axis=1);

print("Your matrix: ", matrix_np);
print("Your minimum number in matrix: ", min_number);
print("Your maximum number in matrix: ", max_number);
print("Your minimum number of each row in matrix: ", min_of_each_row);
print("Your maximum number of each row in matrix: ", max_of_each_row);

Your matrix:  [[ 15   3  56  78]
 [ 16   2  45 100]
 [ 14   4  33  94]
 [ 15   6  67 240]]
Your minimum number in matrix:  2
Your maximum number in matrix:  240
Your minimum number of each row in matrix:  [3 2 4 6]
Your maximum number of each row in matrix:  [ 78 100  94 240]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [12]:
matrix_with_reapit = [[15, 3, 6, 6],
                      [16, 15, 45, 15],
                      [6, 4, 15, 6],
                      [15, 6, 67, 15]
];

unique_elements, counts = np.unique(matrix_with_reapit, return_counts=True)

print("Unique elements:", unique_elements)
print("Counts:", counts)

Unique elements: [ 3  4  6 15 16 45 67]
Counts: [1 1 5 6 1 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [13]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [14]:
data = [
    {"SecondName": "Jackson", "firstName": "Josephine", "BirthDate": "01/03/1995", "Kilograms": 59, "MedicalAssurance": True},
    {"SecondName": "Smith", "firstName": "John", "BirthDate": "12/15/1988", "Kilograms": 82, "MedicalAssurance": False},
    {"SecondName": "Williams", "firstName": "Emily", "BirthDate": "07/22/1992", "Kilograms": 68, "MedicalAssurance": True},
    {"SecondName": "Brown", "firstName": "James", "BirthDate": "03/05/1985", "Kilograms": 75, "MedicalAssurance": True},
    {"SecondName": "Davis", "firstName": "Sophia", "BirthDate": "11/19/1990", "Kilograms": None, "MedicalAssurance": False}
]

dataFrame = pd.DataFrame(data)

print(dataFrame)

print("\nTypes of eack column:\n", dataFrame.dtypes)

  SecondName  firstName   BirthDate  Kilograms  MedicalAssurance
0    Jackson  Josephine  01/03/1995       59.0              True
1      Smith       John  12/15/1988       82.0             False
2   Williams      Emily  07/22/1992       68.0              True
3      Brown      James  03/05/1985       75.0              True
4      Davis     Sophia  11/19/1990        NaN             False

Types of eack column:
 SecondName           object
firstName            object
BirthDate            object
Kilograms           float64
MedicalAssurance       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [33]:
df = pd.read_csv('sample_data/missile_attacks_daily.csv')
print("Your data frame!:\n",df)

Your data frame!:
             time_start          time_end               model  \
0     2025-01-25 19:00  2025-01-26 09:00      Shahed-136/131   
1     2025-01-24 19:00  2025-01-25 09:30      Shahed-136/131   
2     2025-01-24 18:30  2025-01-24 19:30           X-59/X-69   
3     2025-01-23 21:00  2025-01-24 09:00      Shahed-136/131   
4     2025-01-22 19:00  2025-01-23 09:30      Shahed-136/131   
...                ...               ...                 ...   
2051  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2052        2022-09-30        2022-09-30            Orlan-10   
2053  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2054        2022-09-28        2022-09-28                X-59   
2055        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
1     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
2                                  

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [17]:
print("First 10 rows of DataFrame:\n", df.head(10))

First 10 rows of DataFrame:
          time_start          time_end             model  \
0  2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5  2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6  2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7  2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8  2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9  2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primor

14. Отримайте інформацію про форму датафрейму.

In [18]:
print("Shape of data frame", df.shape)

Shape of data frame (2056, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [19]:
print("Info about each column",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   float64
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [20]:
print("Ifo about columns with numbers: \n", df.describe())

Ifo about columns with numbers: 
           launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2053.000000  2056.000000      164.000000             32.000000   
mean     10.872382     7.647860       21.231707              2.312500   
std      21.605295    14.506397       19.812804              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        30.000000  
mean      2.000000         2.766667  
std       1.137593         2.848876  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.750000  
max 

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [21]:
unique_numbers_in_each_column = df.nunique()

min_unique_column = unique_numbers_in_each_column.idxmin()
min_unique_values = df[min_unique_column].value_counts()

print("Unique numbers in each column:\n",unique_numbers_in_each_column)
print(f"The column with the fewest unique values: {min_unique_column}")
print(min_unique_values)

Unique numbers in each column:
 time_start               874
time_end                1025
model                     61
launch_place             136
target                    97
carrier                   58
launched                 117
destroyed                 83
not_reach_goal            56
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        297
launched_details           4
launch_place_details       4
source                   968
dtype: int64
The column with the fewest unique values: launched_details
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Багато пропущених значень
2.   Не правельний формат дати
3.   Багато значень котрі повторюються
4.   Можлива зміна назви колонок чи стовбців, для кращого розуміння


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [22]:
df['launched'] = df['launched'].astype('Int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   Int64  
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [23]:
dfFormated = df.dropna(thresh=len(df) * 0.3, axis=1)
print(dfFormated)


            time_start          time_end               model  \
0     2025-01-25 19:00  2025-01-26 09:00      Shahed-136/131   
1     2025-01-24 19:00  2025-01-25 09:30      Shahed-136/131   
2     2025-01-24 18:30  2025-01-24 19:30           X-59/X-69   
3     2025-01-23 21:00  2025-01-24 09:00      Shahed-136/131   
4     2025-01-22 19:00  2025-01-23 09:30      Shahed-136/131   
...                ...               ...                 ...   
2051  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2052        2022-09-30        2022-09-30            Orlan-10   
2053  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2054        2022-09-28        2022-09-28                X-59   
2055        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
1     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
2                                             Black Se

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [37]:
befor_editing_size = df.shape[0]

df.drop_duplicates(inplace=True)

df = df[df['time_end'] > df['time_start']]

df.reset_index(drop=True, inplace=True)

after_editing_size = df.shape[0]

removed_count = befor_editing_size - after_editing_size

print(f"Number of removed: {removed_count}")

Number of removed: 0


**місце для текстової відповіді**
1221 рядок, це ми підрахували методом збереження форми до та після видалення, потім порівняли це все

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [38]:
print(df[df.isnull().any(axis=1)])

            time_start          time_end           model  \
0     2025-01-25 19:00  2025-01-26 09:00  Shahed-136/131   
1     2025-01-24 19:00  2025-01-25 09:30  Shahed-136/131   
2     2025-01-24 18:30  2025-01-24 19:30       X-59/X-69   
3     2025-01-23 21:00  2025-01-24 09:00  Shahed-136/131   
4     2025-01-22 19:00  2025-01-23 09:30  Shahed-136/131   
...                ...               ...             ...   
1210  2022-10-06 09:00  2022-10-06 11:30       Mohajer-6   
1211        2022-10-06  2022-10-06 02:00  Shahed-136/131   
1212        2022-10-05  2022-10-05 02:00  Shahed-136/131   
1213  2022-10-02 00:00  2022-10-02 02:00  Shahed-136/131   
1214  2022-09-29 23:00  2022-09-29 23:59  Shahed-136/131   

                                           launch_place  \
0     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
1     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
2                                             Black Sea   
3     Primorsko-Akhtarsk and Kursk oblast a